"use client"
import { useState, useEffect } from "react"

const CSS = `@import url('https://fonts.googleapis.com/css2?family=Bebas+Neue&family=DM+Sans:wght@300;400;500;600&family=Space+Mono:wght@400;700&display=swap');*,*::before,*::after{box-sizing:border-box}body{margin:0}.fm{font-family:'DM Sans',sans-serif}.fd{font-family:'Bebas Neue',sans-serif}.fm-code{font-family:'Space Mono',monospace}@keyframes fm-fadeUp{from{opacity:0;transform:translateY(40px)}to{opacity:1;transform:translateY(0)}}@keyframes fm-ticker{0%,100%{transform:scale(1)}45%,55%{transform:scale(1.08)}}@keyframes fm-glow{0%,100%{box-shadow:0 0 20px #FF3D0055}50%{box-shadow:0 0 48px #FF3D00aa,0 0 80px #FF3D0033}}@keyframes fm-pulse{0%,100%{opacity:0.5}50%{opacity:1}}@keyframes fm-float{0%,100%{transform:translateY(0)}50%{transform:translateY(-10px)}}@keyframes fm-marquee{from{transform:translateX(0)}to{transform:translateX(-50%)}}.fm-a1{animation:fm-fadeUp 0.8s ease 0.1s both}.fm-a2{animation:fm-fadeUp 0.8s ease 0.3s both}.fm-a3{animation:fm-fadeUp 0.8s ease 0.5s both}.fm-a4{animation:fm-fadeUp 0.8s ease 0.7s both}.fm-a5{animation:fm-fadeUp 0.8s ease 0.9s both}.fm-card{transition:transform 0.3s ease;cursor:pointer}.fm-card:hover{transform:translateY(-8px)}.fm-btn{transition:all 0.25s ease;cursor:pointer;border:none}.fm-btn:hover{filter:brightness(1.15);transform:translateY(-2px)}.fm-tab{transition:all 0.25s ease;cursor:pointer;border:none;background:none}.fm-marquee-track{display:flex;animation:fm-marquee 24s linear infinite;width:max-content}.fm-grid-bg{background-image:linear-gradient(rgba(255,255,255,0.03) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,0.03) 1px,transparent 1px);background-size:48px 48px}.fm-tag{display:inline-block;padding:3px 10px;border-radius:2px;font-family:'Space Mono',monospace;font-size:10px;letter-spacing:2px;text-transform:uppercase;font-weight:700}`

function StyleInjector(){useEffect(()=>{if(document.getElementById("fm-styles"))return;const el=document.createElement("style");el.id="fm-styles";el.textContent=CSS;document.head.appendChild(el)},[]);return null}

function useCountdown(date:string){const[cd,setCd]=useState({days:0,hours:0,minutes:0,seconds:0});useEffect(()=>{const tick=()=>{const diff=new Date(date).getTime()-Date.now();if(diff<=0)return;setCd({days:Math.floor(diff/86400000),hours:Math.floor((diff%86400000)/3600000),minutes:Math.floor((diff%3600000)/60000),seconds:Math.floor((diff%60000)/1000)})};tick();const id=setInterval(tick,1000);return()=>clearInterval(id)},[date]);return cd}

export function FestivalMicrosite({event}:{event:any}){
  const[scrolled,setScrolled]=useState(false)
  const[activeNav,setActiveNav]=useState("about")
  const[filter,setFilter]=useState("All")
  const[selectedEvent,setSelectedEvent]=useState<any>(null)
  const[submitted,setSubmitted]=useState(false)
  const cd=useCountdown(event.startDate||new Date().toISOString())
  const primaryColor="#FF3D00"
  const festival=event.festival||{}
  const subEvents=festival.sub_events||[]
  const tickets=festival.tickets||[]
  const artists=festival.artists||[]
  const sponsors=festival.sponsors||[]
  const schedule=event.schedule||[]
  
  useEffect(()=>{const fn=()=>setScrolled(window.scrollY>60);window.addEventListener("scroll",fn);return()=>window.removeEventListener("scroll",fn)},[])
  
  const go=(id:string)=>{setActiveNav(id.toLowerCase());document.getElementById(id.toLowerCase())?.scrollIntoView({behavior:"smooth"})}
  const links=["About","Events","Schedule","Tickets","Register","Artists","Sponsors","Contact"]
  const cats=["All",...Array.from(new Set(subEvents.map((e:any)=>e.category)))]
  const shown=filter==="All"?subEvents:subEvents.filter((e:any)=>e.category===filter)
  
  const handleSubmit=async(e:React.FormEvent)=>{
    e.preventDefault()
    const form=e.target as HTMLFormElement
    const data={name:form.fullname.value,email:form.email.value,phone:form.phone.value}
    try{
      const res=await fetch(`http://localhost:5000/api/events/${event.slug}/register`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)})
      if(res.ok){setSubmitted(true);form.reset()}else{let msg='Event not found. Please ensure the event is published.';try{const error=await res.json();msg=error.message||msg}catch(e){}alert(`Registration failed: ${msg}`)}
    }catch(err){console.error('Network error:',err);alert("Registration failed. Please check if the backend is running.")}
  }
  
  return(<div className="fm" style={{minHeight:"100vh",background:"#050505"}}><StyleInjector/><nav style={{position:"fixed",top:0,left:0,right:0,zIndex:300,background:scrolled?"rgba(5,5,5,0.95)":"transparent",backdropFilter:scrolled?"blur(16px)":"none",borderBottom:scrolled?"1px solid rgba(255,61,0,0.2)":"none",padding:scrolled?"14px 48px":"22px 48px",display:"flex",alignItems:"center",justifyContent:"space-between",transition:"all 0.4s ease"}}><div className="fd" style={{fontSize:22,color:primaryColor,letterSpacing:3}}>{event.eventName?.split(" ")[0]}<span style={{color:"#FFD600"}}>FEST</span></div><div style={{display:"flex",gap:28,alignItems:"center"}}>{links.map(l=>(<button key={l} className="fm fm-tab" onClick={()=>go(l)} style={{color:activeNav===l.toLowerCase()?primaryColor:"rgba(255,255,255,0.7)",fontSize:13,letterSpacing:2,textTransform:"uppercase",padding:"4px 0",borderBottom:activeNav===l.toLowerCase()?`1px solid ${primaryColor}`:"1px solid transparent"}}>{l}</button>))}</div><button className="fm-btn fm" onClick={()=>go("Register")} style={{background:primaryColor,color:"#fff",padding:"10px 24px",borderRadius:3,fontSize:13,letterSpacing:2,textTransform:"uppercase",fontWeight:600}}>Register</button></nav>
<section style={{minHeight:"100vh",background:"#050505",position:"relative",display:"flex",alignItems:"center",overflow:"hidden"}}><div className="fm-grid-bg" style={{position:"absolute",inset:0}}/><div style={{position:"absolute",width:600,height:600,borderRadius:"50%",background:"radial-gradient(circle, rgba(255,61,0,0.18) 0%, transparent 70%)",top:"10%",left:"60%",pointerEvents:"none"}}/><div className="fm" style={{maxWidth:1200,margin:"0 auto",padding:"120px 48px 80px",position:"relative",zIndex:2,width:"100%"}}><div style={{display:"grid",gridTemplateColumns:"1fr 420px",gap:80,alignItems:"center"}}><div><div className="fm-a1"><span className="fm-tag" style={{background:"rgba(255,61,0,0.15)",color:primaryColor,border:"1px solid rgba(255,61,0,0.3)",marginBottom:24,display:"inline-block"}}>⚡ {event.startDate} · {event.venue}</span></div><h1 className="fd fm-a2" style={{fontSize:"clamp(64px, 9vw, 120px)",color:"#fff",margin:"0 0 8px",lineHeight:0.9,letterSpacing:4}}>{event.eventName}</h1><p className="fm fm-a3" style={{fontSize:20,color:"rgba(255,255,255,0.55)",margin:"24px 0 0",letterSpacing:1,maxWidth:520}}>{event.description||"No description provided"}</p><div className="fm-a4" style={{display:"flex",gap:14,marginTop:40}}><button className="fm-btn fm" onClick={()=>go("Events")} style={{background:primaryColor,color:"#fff",padding:"16px 32px",borderRadius:3,fontSize:14,letterSpacing:2,textTransform:"uppercase",fontWeight:600,boxShadow:"0 0 32px rgba(255,61,0,0.4)"}}>Explore Events</button><button className="fm-btn fm" onClick={()=>go("Register")} style={{background:"transparent",color:"#fff",padding:"16px 32px",borderRadius:3,fontSize:14,letterSpacing:2,textTransform:"uppercase",fontWeight:600,border:"1px solid rgba(255,255,255,0.25)"}}>Register →</button></div></div><div style={{background:"rgba(255,255,255,0.03)",border:"1px solid rgba(255,61,0,0.2)",borderRadius:8,padding:"40px 32px",backdropFilter:"blur(10px)",animation:"fm-glow 3s ease-in-out infinite"}}><div className="fm-code" style={{fontSize:11,color:primaryColor,letterSpacing:4,textTransform:"uppercase",marginBottom:28,textAlign:"center"}}>— COUNTDOWN —</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}>{[{l:"Days",v:cd.days},{l:"Hours",v:cd.hours},{l:"Minutes",v:cd.minutes},{l:"Seconds",v:cd.seconds}].map(({l,v})=>(<div key={l} style={{background:"#0d0d0d",border:l==="Seconds"?"1px solid rgba(255,61,0,0.4)":"1px solid rgba(255,255,255,0.06)",borderRadius:6,padding:"24px 16px",textAlign:"center",animation:l==="Seconds"?"fm-ticker 1s ease-in-out infinite":"none"}}><div className="fd" style={{fontSize:56,color:"#fff",lineHeight:1}}>{String(v).padStart(2,"0")}</div><div className="fm-code" style={{fontSize:10,color:"rgba(255,255,255,0.35)",letterSpacing:3,marginTop:6,textTransform:"uppercase"}}>{l}</div></div>))}</div></div></div></div></section>
<section id="about" style={{background:"#0a0a0a",padding:"100px 48px"}}><div style={{maxWidth:1200,margin:"0 auto"}}><div className="fm-code" style={{fontSize:11,color:primaryColor,letterSpacing:5,textTransform:"uppercase",marginBottom:20}}>01 — About</div><h2 className="fd" style={{fontSize:"clamp(42px,5vw,72px)",color:"#fff",margin:"0 0 24px",lineHeight:0.95}}>About The<br/><span style={{color:primaryColor}}>Festival</span></h2><p className="fm" style={{fontSize:18,color:"rgba(255,255,255,0.6)",lineHeight:1.8,maxWidth:800}}>{event.description||"No description provided"}</p></div></section>
<section id="events" style={{background:"#050505",padding:"100px 48px"}}><div style={{maxWidth:1200,margin:"0 auto"}}><div className="fm-code" style={{fontSize:11,color:primaryColor,letterSpacing:5,textTransform:"uppercase",marginBottom:16}}>02 — Events</div><div style={{display:"flex",alignItems:"flex-end",justifyContent:"space-between",marginBottom:56}}><h2 className="fd" style={{fontSize:"clamp(42px,5vw,72px)",color:"#fff",margin:0,lineHeight:0.95}}>Compete &<br/><span style={{color:primaryColor}}>Perform</span></h2><div style={{display:"flex",gap:10}}>{cats.map(c=>(<button key={c} className="fm fm-tab" onClick={()=>setFilter(c)} style={{padding:"8px 18px",borderRadius:3,fontSize:12,letterSpacing:2,textTransform:"uppercase",fontWeight:600,background:filter===c?primaryColor:"rgba(255,255,255,0.05)",color:filter===c?"#fff":"rgba(255,255,255,0.5)",border:filter===c?"none":"1px solid rgba(255,255,255,0.1)"}}>{c}</button>))}</div></div><div style={{display:"grid",gridTemplateColumns:"repeat(3, 1fr)",gap:20}}>{shown.length>0?shown.map((ev:any,i:number)=>(<div key={i} className="fm-card" onClick={()=>setSelectedEvent(ev)} style={{background:"rgba(255,255,255,0.03)",border:"1px solid rgba(255,255,255,0.07)",borderRadius:8,overflow:"hidden"}}><div style={{height:3,background:i%3===0?primaryColor:i%3===1?"#FFD600":"#fff",opacity:i%3===2?0.2:1}}/><div style={{padding:"32px 28px"}}><span className="fm-tag" style={{background:"rgba(255,61,0,0.1)",color:primaryColor,border:"1px solid rgba(255,61,0,0.2)",marginBottom:12,display:"inline-block"}}>{ev.category}</span><h3 className="fd" style={{fontSize:30,color:"#fff",margin:"0 0 12px",letterSpacing:2}}>{ev.name}</h3><p className="fm" style={{fontSize:14,color:"rgba(255,255,255,0.45)",lineHeight:1.7,margin:"0 0 24px"}}>{ev.description}</p><div className="fm-code" style={{fontSize:11,color:"rgba(255,255,255,0.3)"}}>📅 {ev.date} · {ev.time}</div></div></div>)):<p className="fm" style={{color:"rgba(255,255,255,0.4)",gridColumn:"1/-1",textAlign:"center",padding:"40px"}}>No events added yet</p>}</div></div></section>
<section id="schedule" style={{background:"#0a0a0a",padding:"100px 48px"}}><div style={{maxWidth:1200,margin:"0 auto"}}><div className="fm-code" style={{fontSize:11,color:primaryColor,letterSpacing:5,textTransform:"uppercase",marginBottom:16}}>03 — Schedule</div><h2 className="fd" style={{fontSize:"clamp(42px,5vw,72px)",color:"#fff",margin:"0 0 48px",lineHeight:0.95}}>Event<br/><span style={{color:primaryColor}}>Timeline</span></h2>{schedule.length>0?schedule.map((item:any,i:number)=>(<div key={i} style={{display:"grid",gridTemplateColumns:"120px 1fr",gap:0,borderBottom:"1px solid rgba(255,255,255,0.05)"}}><div style={{padding:"24px 0",borderRight:"1px solid rgba(255,61,0,0.2)",paddingRight:24}}><div className="fm-code" style={{fontSize:13,color:primaryColor}}>{item.time}</div></div><div style={{padding:"24px 32px"}}><div className="fm" style={{fontSize:18,fontWeight:600,color:"#fff"}}>{item.title}</div></div></div>)):<p className="fm" style={{color:"rgba(255,255,255,0.4)"}}>Schedule coming soon</p>}</div></section>
<section id="tickets" style={{background:"#050505",padding:"100px 48px"}}><div style={{maxWidth:1200,margin:"0 auto"}}><div className="fm-code" style={{fontSize:11,color:primaryColor,letterSpacing:5,textTransform:"uppercase",marginBottom:16}}>04 — Passes</div><h2 className="fd" style={{fontSize:"clamp(42px,5vw,72px)",color:"#fff",margin:"0 0 56px",lineHeight:0.95}}>Get Your<br/><span style={{color:primaryColor}}>Pass</span></h2>{tickets.length>0?(<div style={{display:"grid",gridTemplateColumns:"repeat(3, 1fr)",gap:24}}>{tickets.map((t:any,i:number)=>(<div key={i} className="fm-card" style={{background:"rgba(255,255,255,0.03)",border:"1px solid rgba(255,255,255,0.08)",borderRadius:8,padding:"40px 32px"}}><div className="fd" style={{fontSize:26,color:"rgba(255,255,255,0.6)",letterSpacing:2,marginBottom:8}}>{t.name}</div><div className="fd" style={{fontSize:56,color:primaryColor,lineHeight:1,marginBottom:28}}>₹{t.price}</div><p className="fm" style={{fontSize:14,color:"rgba(255,255,255,0.4)",marginBottom:28}}>{t.description}</p><button className="fm-btn fm" onClick={()=>go("register")} style={{width:"100%",padding:"14px",borderRadius:4,fontSize:13,fontWeight:700,letterSpacing:2,textTransform:"uppercase",background:primaryColor,color:"#fff"}}>Buy {t.name}</button></div>))}</div>):(<div style={{textAlign:"center",padding:"60px 20px",background:"rgba(255,255,255,0.02)",borderRadius:8,border:"1px solid rgba(255,255,255,0.05)"}}><p className="fm" style={{fontSize:18,color:"rgba(255,255,255,0.5)",marginBottom:32}}>Registration is free for this festival</p><button className="fm-btn fm" onClick={()=>go("register")} style={{padding:"16px 48px",borderRadius:4,fontSize:14,fontWeight:700,letterSpacing:2,textTransform:"uppercase",background:primaryColor,color:"#fff"}}>Register Now</button></div>)}</div></section>
<section id="register" style={{background:"#0a0a0a",padding:"100px 48px"}}><div style={{maxWidth:600,margin:"0 auto"}}><div className="fm-code" style={{fontSize:11,color:primaryColor,letterSpacing:5,textTransform:"uppercase",marginBottom:16,textAlign:"center"}}>Register</div><h2 className="fd" style={{fontSize:"clamp(42px,5vw,72px)",color:"#fff",margin:"0 0 48px",lineHeight:0.95,textAlign:"center"}}>Join The<br/><span style={{color:primaryColor}}>Festival</span></h2>{submitted?(<div style={{textAlign:"center",padding:"60px 40px",background:"rgba(34,197,94,0.1)",border:"1px solid rgba(34,197,94,0.3)",borderRadius:8}}><div style={{fontSize:64,marginBottom:20}}>🎉</div><h3 className="fd" style={{fontSize:36,color:"#fff",marginBottom:12}}>You're Registered!</h3><p className="fm" style={{fontSize:16,color:"rgba(255,255,255,0.7)"}}>Check your email for confirmation details</p></div>):(<div style={{background:"rgba(255,255,255,0.03)",border:"1px solid rgba(255,255,255,0.08)",borderRadius:8,padding:"48px 40px"}}><form onSubmit={handleSubmit} style={{display:"flex",flexDirection:"column",gap:24}}><div><label className="fm" style={{display:"block",fontSize:13,color:"rgba(255,255,255,0.6)",marginBottom:8,letterSpacing:1}}>Full Name *</label><input name="fullname" required style={{width:"100%",padding:"14px 16px",background:"rgba(255,255,255,0.05)",border:"1px solid rgba(255,255,255,0.1)",borderRadius:4,color:"#fff",fontSize:15,fontFamily:"inherit"}} placeholder="Your full name"/></div><div><label className="fm" style={{display:"block",fontSize:13,color:"rgba(255,255,255,0.6)",marginBottom:8,letterSpacing:1}}>Email *</label><input name="email" type="email" required style={{width:"100%",padding:"14px 16px",background:"rgba(255,255,255,0.05)",border:"1px solid rgba(255,255,255,0.1)",borderRadius:4,color:"#fff",fontSize:15,fontFamily:"inherit"}} placeholder="your@email.com"/></div><div><label className="fm" style={{display:"block",fontSize:13,color:"rgba(255,255,255,0.6)",marginBottom:8,letterSpacing:1}}>Phone</label><input name="phone" type="tel" style={{width:"100%",padding:"14px 16px",background:"rgba(255,255,255,0.05)",border:"1px solid rgba(255,255,255,0.1)",borderRadius:4,color:"#fff",fontSize:15,fontFamily:"inherit"}} placeholder="+91 98765 43210"/></div><button type="submit" className="fm-btn fm" style={{width:"100%",padding:"16px",borderRadius:4,fontSize:14,fontWeight:700,letterSpacing:2,textTransform:"uppercase",background:primaryColor,color:"#fff",marginTop:8}}>Complete Registration</button></form></div>)}</div></section>
<section id="artists" style={{background:"#0a0a0a",padding:"100px 48px"}}><div style={{maxWidth:1200,margin:"0 auto"}}><div className="fm-code" style={{fontSize:11,color:primaryColor,letterSpacing:5,textTransform:"uppercase",marginBottom:16}}>05 — Artists</div><h2 className="fd" style={{fontSize:"clamp(42px,5vw,72px)",color:"#fff",margin:"0 0 56px",lineHeight:0.95}}>Who's<br/><span style={{color:primaryColor}}>Performing?</span></h2><div style={{display:"grid",gridTemplateColumns:"repeat(4, 1fr)",gap:20}}>{artists.length>0?artists.map((a:any,i:number)=>(<div key={i} className="fm-card" style={{background:"rgba(255,255,255,0.03)",border:"1px solid rgba(255,255,255,0.07)",borderRadius:8,overflow:"hidden"}}><div style={{height:160,background:`linear-gradient(135deg, #${["1a0800","001a08","00081a","1a001a"][i%4]}, #0d0d0d)`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:64,position:"relative"}}>🎵<div style={{position:"absolute",bottom:0,left:0,right:0,height:2,background:["#FF3D00","#FFD600","#FF3D00","#FFD600"][i%4]}}/></div><div style={{padding:"24px 20px"}}><div className="fd" style={{fontSize:22,color:"#fff",letterSpacing:2,marginBottom:4}}>{a.name}</div><div className="fm-tag" style={{background:"rgba(255,61,0,0.1)",color:primaryColor,border:"1px solid rgba(255,61,0,0.2)",marginBottom:14}}>{a.type}</div><div className="fm-code" style={{fontSize:11,color:"rgba(255,255,255,0.3)",lineHeight:1.6}}>🕐 {a.date} {a.time}<br/>📍 {a.stage}</div></div></div>)):<p className="fm" style={{color:"rgba(255,255,255,0.4)",gridColumn:"1/-1",textAlign:"center",padding:"40px"}}>Artist lineup coming soon</p>}</div></div></section>
<section id="sponsors" style={{background:"#050505",padding:"80px 48px",borderTop:"1px solid rgba(255,255,255,0.05)"}}><div style={{maxWidth:1200,margin:"0 auto"}}><div className="fm-code" style={{fontSize:11,color:"rgba(255,255,255,0.25)",letterSpacing:5,textTransform:"uppercase",marginBottom:40,textAlign:"center"}}>Our Sponsors & Partners</div><div style={{display:"grid",gridTemplateColumns:"repeat(6, 1fr)",gap:16}}>{sponsors.length>0?sponsors.map((s:any,i:number)=>(<div key={i} className="fm-card" style={{background:"rgba(255,255,255,0.03)",border:"1px solid rgba(255,255,255,0.06)",borderRadius:6,padding:"24px 16px",textAlign:"center"}}><div style={{fontSize:28,marginBottom:8}}>🏢</div><div className="fm" style={{fontSize:13,fontWeight:600,color:"rgba(255,255,255,0.7)",marginBottom:4}}>{s.name}</div><div className="fm-code" style={{fontSize:9,color:"rgba(255,255,255,0.25)",letterSpacing:2}}>{s.category}</div></div>)):<p className="fm" style={{color:"rgba(255,255,255,0.4)",gridColumn:"1/-1",textAlign:"center",padding:"40px"}}>Sponsor information coming soon</p>}</div></div></section>
<section id="contact" style={{background:"#0a0a0a",padding:"100px 48px"}}><div style={{maxWidth:800,margin:"0 auto",textAlign:"center"}}><div className="fm-code" style={{fontSize:11,color:primaryColor,letterSpacing:5,textTransform:"uppercase",marginBottom:16}}>06 — Contact</div><h2 className="fd" style={{fontSize:"clamp(42px,5vw,72px)",color:"#fff",margin:"0 0 24px",lineHeight:0.95}}>Get In<br/><span style={{color:primaryColor}}>Touch</span></h2><p className="fm" style={{fontSize:17,color:"rgba(255,255,255,0.45)",lineHeight:1.8}}>Questions? Contact us at {event.contact?.email||"info@festival.com"}</p></div></section>
<footer style={{background:"#000",borderTop:"1px solid rgba(255,61,0,0.15)",padding:"48px",textAlign:"center"}}><div className="fd" style={{fontSize:40,color:primaryColor,letterSpacing:4,marginBottom:8}}>{event.eventName}</div><p className="fm" style={{fontSize:12,color:"rgba(255,255,255,0.2)",margin:0}}>Powered by EventSphere</p></footer></div>)}
